Repository DongSanOfficial/DongSan-Backend, pull requests merged in 2024-12, with the labels that each got.

#17 [feature/DB-66]: 산책로 좋아요 API
  dongsan-api/src/main/java/com/dongsan/domains/user/usecase/UserProfileUseCase.java
  dongsan-api/src/main/java/com/dongsan/domains/walkway/controller/LikedWalkwayController.java
  dongsan-api/src/main/java/com/dongsan/domains/walkway/controller/WalkwayController.java
  dongsan-api/src/main/java/com/dongsan/domains/walkway/mapper/LikedWalkwayMapper.java
  dongsan-api/src/main/java/com/dongsan/domains/walkway/usecase/LikedWalkwayUseCase.java
  dongsan-api/src/main/java/com/dongsan/domains/walkway/usecase/WalkwayReviewUseCase.java
  dongsan-api/src/main/java/com/dongsan/domains/walkway/usecase/WalkwayUseCase.java
  dongsan-api/src/test/java/com/dongsan/domains/user/controller/UserProfileControllerTest.java
  dongsan-api/src/test/java/com/dongsan/domains/user/usecase/UserProfileUseCaseTest.java
  dongsan-api/src/test/java/com/dongsan/domains/walkway/controller/LikedWalkwayControllerTest.java
  dongsan-api/src/test/java/com/dongsan/domains/walkway/controller/ReviewControllerTest.java
  dongsan-api/src/test/java/com/dongsan/domains/walkway/controller/WalkwayControllerTest.java
  dongsan-api/src/test/java/com/dongsan/domains/walkway/usecase/LikedWalkwayUseCaseTest.java
  dongsan-api/src/test/java/com/dongsan/domains/walkway/usecase/WalkwayReviewUseCaseTest.java
  dongsan-api/src/test/java/com/dongsan/domains/walkway/usecase/WalkwayUseCaseTest.java
  dongsan-domain/src/main/java/com/dongsan/domains/member/service/MemberQueryService.java
  dongsan-domain/src/main/java/com/dongsan/domains/walkway/repository/LikedWalkwayRepository.java
  dongsan-domain/src/main/java/com/dongsan/domains/walkway/service/LikedWalkwayCommandService.java
  dongsan-domain/src/main/java/com/dongsan/domains/walkway/service/WalkwayQueryService.java
  dongsan-domain/src/test/java/com/dongsan/domains/member/service/MemberQueryServiceTest.java
  dongsan-domain/src/test/java/com/dongsan/domains/walkway/service/LikedWalkwayCommandServiceTest.java
  dongsan-domain/src/test/java/com/dongsan/domains/walkway/service/WalkwayQueryServiceTest.java
Labels: ✅ Test, ✨ Feature

#18 [feature/DB-65]: 북마크 생성, 이름 변경 API
  dongsan-api/src/main/java/com/dongsan/common/validation/annotation/ExistBookmark.java
  dongsan-api/src/main/java/com/dongsan/common/validation/validator/ExistBookmarkValidator.java
  dongsan-api/src/main/java/com/dongsan/domains/bookmark/controller/BookmarkController.java
  dongsan-api/src/main/java/com/dongsan/domains/bookmark/dto/request/BookmarkNameRequest.java
  dongsan-api/src/main/java/com/dongsan/domains/bookmark/dto/response/BookmarkIdResponse.java
  dongsan-api/src/main/java/com/dongsan/domains/bookmark/mapper/BookmarkMapper.java
  dongsan-api/src/main/java/com/dongsan/domains/bookmark/usecase/BookmarkUseCase.java
  dongsan-api/src/test/java/com/dongsan/domains/bookmark/controller/BookmarkControllerTest.java
  dongsan-api/src/test/java/com/dongsan/domains/bookmark/usecase/BookmarkUseCaseTest.java
  dongsan-api/src/test/java/com/dongsan/domains/dev/controller/DevTokenControllerTest.java
  dongsan-api/src/test/java/com/dongsan/domains/user/controller/UserReviewControllerTest.java
  dongsan-common/src/main/java/com/dongsan/error/code/BookmarkErrorCode.java
  dongsan-domain/src/main/java/com/dongsan/domains/bookmark/entity/Bookmark.java
  dongsan-domain/src/main/java/com/dongsan/domains/bookmark/repository/BookmarkRepository.java
  dongsan-domain/src/main/java/com/dongsan/domains/bookmark/service/BookmarkCommandService.java
  dongsan-domain/src/main/java/com/dongsan/domains/bookmark/service/BookmarkQueryService.java
  dongsan-domain/src/test/java/com/dongsan/domains/bookmark/service/BookmarkCommandServiceTest.java
  dongsan-domain/src/test/java/com/dongsan/domains/bookmark/service/BookmarkQueryServiceTest.java
Labels: ✅ Test, ✨ Feature

#19 [feature/DB-76]: 산책로 수정, 산책로 북마크 리스트 API
  dongsan-api/src/main/java/com/dongsan/domains/bookmark/dto/response/BookmarksWithMarkedWalkwayResponse.java
  dongsan-api/src/main/java/com/dongsan/domains/bookmark/mapper/BookmarksWithMarkedWalkwayMapper.java
  dongsan-api/src/main/java/com/dongsan/domains/bookmark/usecase/BookmarkUseCase.java
  dongsan-api/src/main/java/com/dongsan/domains/user/usecase/UserProfileUseCase.java
  dongsan-api/src/main/java/com/dongsan/domains/walkway/controller/WalkwayController.java
  dongsan-api/src/main/java/com/dongsan/domains/walkway/dto/request/CreateWalkwayRequest.java
  dongsan-api/src/main/java/com/dongsan/domains/walkway/dto/request/UpdateWalkwayRequest.java
  dongsan-api/src/main/java/com/dongsan/domains/walkway/usecase/HashtagUseCase.java
  dongsan-api/src/main/java/com/dongsan/domains/walkway/usecase/LikedWalkwayUseCase.java
  dongsan-api/src/main/java/com/dongsan/domains/walkway/usecase/WalkwayUseCase.java
  dongsan-api/src/test/java/com/dongsan/domains/bookmark/usecase/BookmarkUseCaseTest.java
  dongsan-api/src/test/java/com/dongsan/domains/user/usecase/UserProfileUseCaseTest.java
  dongsan-api/src/test/java/com/dongsan/domains/walkway/controller/WalkwayControllerTest.java
  dongsan-api/src/test/java/com/dongsan/domains/walkway/usecase/HashtagUseCaseTest.java
  dongsan-api/src/test/java/com/dongsan/domains/walkway/usecase/WalkwayUseCaseTest.java
  dongsan-common/src/main/java/com/dongsan/error/code/WalkwayErrorCode.java
  dongsan-domain/src/main/java/com/dongsan/domains/bookmark/entity/Bookmark.java
  dongsan-domain/src/main/java/com/dongsan/domains/bookmark/repository/BookmarkQueryDSLRepository.java
  dongsan-domain/src/main/java/com/dongsan/domains/bookmark/service/BookmarkQueryService.java
  dongsan-domain/src/main/java/com/dongsan/domains/hashtag/repository/HashtagWalkwayRepository.java
  dongsan-domain/src/main/java/com/dongsan/domains/hashtag/service/HashtagWalkwayCommandService.java
  dongsan-domain/src/main/java/com/dongsan/domains/walkway/entity/Walkway.java
  dongsan-domain/src/main/java/com/dongsan/domains/walkway/repository/WalkwayQueryDSLRepository.java
  dongsan-domain/src/main/java/com/dongsan/domains/walkway/service/WalkwayQueryService.java
  dongsan-domain/src/test/java/com/dongsan/domains/bookmark/repository/BookmarkQueryDSLRepositoryTest.java
  dongsan-domain/src/test/java/com/dongsan/domains/bookmark/service/BookmarkQueryServiceTest.java
  dongsan-domain/src/test/java/com/dongsan/domains/hashtag/service/HashtagWalkwayCommandServiceTest.java
  dongsan-domain/src/test/java/com/dongsan/domains/walkway/repository/WalkwayQueryDSLRepositoryTest.java
  dongsan-domain/src/test/java/com/dongsan/domains/walkway/service/WalkwayQueryServiceTest.java
  dongsan-domain/src/testFixtures/java/fixture/MarkedWalkwayFixture.java
Labels: ✅ Test, ✨ Feature

#20 [refactor/DB-84]: 북마크 연관관계 API 수정
  dongsan-api/src/main/java/com/dongsan/domains/bookmark/mapper/BookmarksWithMarkedWalkwayMapper.java
  dongsan-api/src/main/java/com/dongsan/domains/bookmark/usecase/BookmarkUseCase.java
  dongsan-api/src/test/java/com/dongsan/domains/bookmark/usecase/BookmarkUseCaseTest.java
  dongsan-api/src/test/java/com/dongsan/domains/walkway/controller/WalkwayControllerTest.java
  dongsan-domain/src/main/java/com/dongsan/domains/bookmark/dto/BookmarksWithMarkedWalkwayDTO.java
  dongsan-domain/src/main/java/com/dongsan/domains/bookmark/repository/BookmarkQueryDSLRepository.java
  dongsan-domain/src/main/java/com/dongsan/domains/bookmark/service/BookmarkQueryService.java
  dongsan-domain/src/test/java/com/dongsan/domains/bookmark/repository/BookmarkQueryDSLRepositoryTest.java
  dongsan-domain/src/test/java/com/dongsan/domains/bookmark/service/BookmarkQueryServiceTest.java
Labels: ♻️ Refactor

#21 [feature/DB-75]: 북마크에 산책로를 추가&제거 API
  dongsan-api/src/main/java/com/dongsan/domains/bookmark/controller/BookmarkController.java
  dongsan-api/src/main/java/com/dongsan/domains/bookmark/dto/request/WalkwayIdRequest.java
  dongsan-api/src/main/java/com/dongsan/domains/bookmark/usecase/BookmarkUseCase.java
  dongsan-api/src/test/java/com/dongsan/domains/bookmark/controller/BookmarkControllerTest.java
  dongsan-api/src/test/java/com/dongsan/domains/bookmark/usecase/BookmarkUseCaseTest.java
  dongsan-common/src/main/java/com/dongsan/error/code/BookmarkErrorCode.java
  dongsan-domain/src/main/java/com/dongsan/domains/bookmark/entity/Bookmark.java
  dongsan-domain/src/main/java/com/dongsan/domains/bookmark/repository/MarkedWalkwayRepository.java
  dongsan-domain/src/main/java/com/dongsan/domains/bookmark/service/BookmarkCommandService.java
  dongsan-domain/src/main/java/com/dongsan/domains/bookmark/service/BookmarkQueryService.java
  dongsan-domain/src/test/java/com/dongsan/domains/bookmark/repository/MarkedWalkwayRepositoryTest.java
  dongsan-domain/src/test/java/com/dongsan/domains/bookmark/service/BookmarkCommandServiceTest.java
  dongsan-domain/src/test/java/com/dongsan/domains/bookmark/service/BookmarkQueryServiceTest.java
Labels: ✅ Test, ✨ Feature

#23 [hotfix/DB-90]: security filter 경로 수정
  dongsan-api/src/main/java/com/dongsan/config/SecurityConfig.java
Labels: 🚑 Hotfix

#24 [hotfix/DB-91]: 로그인 403 에러 수정
  dongsan-api/src/main/java/com/dongsan/config/SecurityConfig.java
Labels: 🚑 Hotfix

#25 [refactor/DB-92]: 화면 의존적이지 않게 API 수정
  .DS_Store
  dongsan-api/src/main/java/com/dongsan/domains/user/controller/UserReviewController.java
  dongsan-api/src/main/java/com/dongsan/domains/user/controller/UserWalkwayController.java
  dongsan-api/src/main/java/com/dongsan/domains/user/dto/response/GetWalkwayDetailResponse.java
  dongsan-api/src/main/java/com/dongsan/domains/user/dto/response/GetWalkwaySummaryResponse.java
  dongsan-api/src/main/java/com/dongsan/domains/user/dto/response/WalkwayListResponse.java
  dongsan-api/src/main/java/com/dongsan/domains/user/dto/response/WalkwayResponse.java
  dongsan-api/src/main/java/com/dongsan/domains/user/mapper/UserWalkwayMapper.java
  dongsan-api/src/main/java/com/dongsan/domains/user/usecase/UserReviewUseCase.java
  dongsan-api/src/main/java/com/dongsan/domains/user/usecase/UserWalkwayUseCase.java
  dongsan-api/src/main/java/com/dongsan/domains/walkway/controller/WalkwayController.java
  dongsan-api/src/test/java/com/dongsan/domains/user/controller/UserReviewControllerTest.java
  dongsan-api/src/test/java/com/dongsan/domains/user/controller/UserWalkwayControllerTest.java
  dongsan-api/src/test/java/com/dongsan/domains/user/usecase/UserReviewUseCaseTest.java
  dongsan-api/src/test/java/com/dongsan/domains/user/usecase/UserWalkwayUseCaseTest.java
  dongsan-common/src/main/java/com/dongsan/error/code/ReviewErrorCode.java
  dongsan-domain/src/main/java/com/dongsan/domains/review/repository/ReviewQueryDSLRepository.java
  dongsan-domain/src/main/java/com/dongsan/domains/review/repository/ReviewRepository.java
  dongsan-domain/src/main/java/com/dongsan/domains/review/service/ReviewQueryService.java
  dongsan-domain/src/main/java/com/dongsan/domains/walkway/repository/LikedWalkwayQueryDSLRepository.java
  dongsan-domain/src/main/java/com/dongsan/domains/walkway/repository/WalkwayQueryDSLRepository.java
  dongsan-domain/src/main/java/com/dongsan/domains/walkway/repository/WalkwayRepository.java
  dongsan-domain/src/main/java/com/dongsan/domains/walkway/service/LikedWalkwayQueryService.java
  dongsan-domain/src/main/java/com/dongsan/domains/walkway/service/WalkwayQueryService.java
  dongsan-domain/src/test/java/com/dongsan/domains/review/repository/ReviewQueryDSLRepositoryTest.java
  dongsan-domain/src/test/java/com/dongsan/domains/review/service/ReviewQueryServiceTest.java
  dongsan-domain/src/test/java/com/dongsan/domains/walkway/repository/LikedWalkwayQueryDSLRepositoryTest.java
  dongsan-domain/src/test/java/com/dongsan/domains/walkway/repository/WalkwayQueryDSLRepositoryTest.java
  dongsan-domain/src/test/java/com/dongsan/domains/walkway/service/LikedWalkwayQueryServiceTest.java
  dongsan-domain/src/test/java/com/dongsan/domains/walkway/service/WalkwayQueryServiceTest.java
  dongsan-domain/src/testFixtures/java/fixture/ReflectFixture.java
Labels: ♻️ Refactor

#27 [feature/DB-99]: 산책로 검색, 단건 조회 API 수정
  app-external-api/src/main/java/com/dongsan/domains/bookmark/usecase/BookmarkUseCase.java
  app-external-api/src/main/java/com/dongsan/domains/walkway/controller/ReviewController.java
  app-external-api/src/main/java/com/dongsan/domains/walkway/controller/WalkwayController.java
  app-external-api/src/main/java/com/dongsan/domains/walkway/dto/response/GetWalkwaySearchResponse.java
  app-external-api/src/main/java/com/dongsan/domains/walkway/dto/response/GetWalkwayWithLikedResponse.java
  app-external-api/src/main/java/com/dongsan/domains/walkway/mapper/WalkwayMapper.java
  app-external-api/src/main/java/com/dongsan/domains/walkway/usecase/LikedWalkwayUseCase.java
  app-external-api/src/main/java/com/dongsan/domains/walkway/usecase/WalkwayReviewUseCase.java
  app-external-api/src/main/java/com/dongsan/domains/walkway/usecase/WalkwayUseCase.java
  app-external-api/src/test/java/com/dongsan/domains/bookmark/usecase/BookmarkUseCaseTest.java
  app-external-api/src/test/java/com/dongsan/domains/walkway/controller/WalkwayControllerTest.java
  app-external-api/src/test/java/com/dongsan/domains/walkway/usecase/LikedWalkwayUseCaseTest.java
  app-external-api/src/test/java/com/dongsan/domains/walkway/usecase/WalkwayReviewUseCaseTest.java
  app-external-api/src/test/java/com/dongsan/domains/walkway/usecase/WalkwayUseCaseTest.java
  domain/domain-rdb/src/main/java/com/dongsan/domains/review/repository/ReviewRepository.java
  domain/domain-rdb/src/main/java/com/dongsan/domains/review/service/ReviewQueryService.java
  domain/domain-rdb/src/main/java/com/dongsan/domains/walkway/dto/SearchWalkwayPopular.java
  domain/domain-rdb/src/main/java/com/dongsan/domains/walkway/dto/SearchWalkwayRating.java
  domain/domain-rdb/src/main/java/com/dongsan/domains/walkway/entity/Walkway.java
  domain/domain-rdb/src/main/java/com/dongsan/domains/walkway/repository/LikedWalkwayRepository.java
  domain/domain-rdb/src/main/java/com/dongsan/domains/walkway/repository/WalkwayQueryDSLRepository.java
  domain/domain-rdb/src/main/java/com/dongsan/domains/walkway/service/LikedWalkwayQueryService.java
  domain/domain-rdb/src/main/java/com/dongsan/domains/walkway/service/WalkwayQueryService.java
  domain/domain-rdb/src/test/java/com/dongsan/domains/walkway/repository/WalkwayQueryDSLRepositoryTest.java
  domain/domain-rdb/src/test/java/com/dongsan/domains/walkway/service/LikedWalkwayQueryServiceTest.java
  domain/domain-rdb/src/test/java/com/dongsan/domains/walkway/service/WalkwayQueryServiceTest.java
Labels: ♻️ Refactor, 🐞 Fix
