Repository DongSanOfficial/DongSan-Backend, pull requests merged in 2025-02, with the labels that each got.

#38 [feature/DB-136]: 산책로 이용 기록 API
  app-external-api/src/main/java/com/dongsan/domains/walkway/controller/WalkwayController.java
  app-external-api/src/test/java/com/dongsan/domains/walkway/controller/ReviewControllerTest.java
  app-external-api/src/test/java/com/dongsan/domains/walkway/controller/WalkwayControllerTest.java
  core-domain/src/main/java/com/dongsan/domains/walkway/dto/request/CreateReviewRequest.java
  core-domain/src/main/java/com/dongsan/domains/walkway/dto/request/CreateWalkwayHistoryRequest.java
  core-domain/src/main/java/com/dongsan/domains/walkway/dto/response/CreateWalkwayHistoryResponse.java
  core-domain/src/main/java/com/dongsan/domains/walkway/dto/response/GetWalkwayHistoriesResponse.java
  core-domain/src/main/java/com/dongsan/domains/walkway/dto/response/GetWalkwayWithLikedResponse.java
  core-domain/src/main/java/com/dongsan/domains/walkway/mapper/WalkwayHistoryMapper.java
  core-domain/src/main/java/com/dongsan/domains/walkway/service/WalkwayHistoryCommandService.java
  core-domain/src/main/java/com/dongsan/domains/walkway/service/WalkwayHistoryQueryService.java
  core-domain/src/main/java/com/dongsan/domains/walkway/service/WalkwayQueryService.java
  core-domain/src/main/java/com/dongsan/domains/walkway/usecase/WalkwayHistoryUseCase.java
  core-domain/src/main/java/com/dongsan/domains/walkway/usecase/WalkwayReviewUseCase.java
  core-domain/src/main/java/com/dongsan/domains/walkway/usecase/WalkwayUseCase.java
  core-domain/src/test/java/com/dongsan/domains/walkway/service/WalkwayHistoryCommandServiceTest.java
  core-domain/src/test/java/com/dongsan/domains/walkway/service/WalkwayHistoryQueryServiceTest.java
  core-domain/src/test/java/com/dongsan/domains/walkway/service/WalkwayQueryServiceTest.java
  core-domain/src/test/java/com/dongsan/domains/walkway/usecase/WalkwayHistoryUseCaseTest.java
  core-domain/src/test/java/com/dongsan/domains/walkway/usecase/WalkwayReviewUseCaseTest.java
  core-domain/src/test/java/com/dongsan/domains/walkway/usecase/WalkwayUseCaseTest.java
  infrastructure/storage-rdb/src/main/java/com/dongsan/common/error/code/ReviewErrorCode.java
  infrastructure/storage-rdb/src/main/java/com/dongsan/common/error/code/WalkwayHistoryErrorCode.java
  infrastructure/storage-rdb/src/main/java/com/dongsan/domains/bookmark/repository/MarkedWalkwayQueryDSLRepository.java
  infrastructure/storage-rdb/src/main/java/com/dongsan/domains/walkway/entity/WalkwayHistory.java
  infrastructure/storage-rdb/src/main/java/com/dongsan/domains/walkway/repository/WalkwayHistoryQueryDSLRepository.java
  infrastructure/storage-rdb/src/main/java/com/dongsan/domains/walkway/repository/WalkwayHistoryRepository.java
  infrastructure/storage-rdb/src/test/java/com/dongsan/common/config/TestQueryDSLConfig.java
  infrastructure/storage-rdb/src/test/java/com/dongsan/domains/bookmark/repository/MarkedWalkwayQueryDSLRepositoryTest.java
  infrastructure/storage-rdb/src/test/java/com/dongsan/domains/walkway/repository/WalkwayHistoryQueryDSLRepositoryTest.java
  infrastructure/storage-rdb/src/testFixtures/java/fixture/WalkwayHistoryFixture.java
Labels: ♻️ Refactor, ✨ Feature

#40 [hotfix/DB-144]: 토큰 만료기간 확인 API - Refresh Token 로직 수정
  app-external-api/src/main/java/com/dongsan/domains/auth/service/JwtService.java
  app-external-api/src/main/java/com/dongsan/domains/auth/usecase/AuthUseCase.java
Labels: 🚑 Hotfix

#41 [feature/DB-149]: 산책로 이용기록 생성 수정
  app-external-api/src/main/java/com/dongsan/domains/walkway/controller/WalkwayController.java
  app-external-api/src/test/java/com/dongsan/domains/walkway/controller/WalkwayControllerTest.java
  core-domain/src/main/java/com/dongsan/domains/walkway/dto/response/CreateWalkwayHistoryResponse.java
  core-domain/src/main/java/com/dongsan/domains/walkway/usecase/WalkwayHistoryUseCase.java
  core-domain/src/test/java/com/dongsan/domains/walkway/usecase/WalkwayHistoryUseCaseTest.java
Labels: 🐞 Fix

#43 [hotfix/DB-153]: 쿠키, 리다이렉팅 코드 수정
  app-external-api/src/main/java/com/dongsan/domains/auth/security/oauth2/handler/CustomSuccessHandler.java
  app-external-api/src/main/java/com/dongsan/domains/auth/service/CookieService.java
Labels: 🚑 Hotfix

#46 [feature/DB-145]: 모듈 별 예외처리 구분
  app-external-api/src/main/java/com/dongsan/api/domains/auth/controller/AuthController.java
  app-external-api/src/main/java/com/dongsan/api/domains/auth/security/filter/AuthFilter.java
  app-external-api/src/main/java/com/dongsan/api/domains/auth/security/handler/CustomAccessDeniedHandler.java
  app-external-api/src/main/java/com/dongsan/api/domains/auth/security/handler/CustomAuthenticationEntryPoint.java
  app-external-api/src/main/java/com/dongsan/api/domains/auth/service/JwtService.java
  app-external-api/src/main/java/com/dongsan/api/domains/auth/usecase/AuthUseCase.java
  app-external-api/src/main/java/com/dongsan/api/domains/bookmark/BookmarkController.java
  app-external-api/src/main/java/com/dongsan/api/domains/dev/DevController.java
  app-external-api/src/main/java/com/dongsan/api/domains/dev/DevUseCase.java
  app-external-api/src/main/java/com/dongsan/api/domains/image/S3UseCase.java
  app-external-api/src/main/java/com/dongsan/api/domains/user/UserProfileController.java
  app-external-api/src/main/java/com/dongsan/api/domains/user/UserReviewController.java
  app-external-api/src/main/java/com/dongsan/api/domains/user/UserWalkwayController.java
  app-external-api/src/main/java/com/dongsan/api/domains/walkway/LikedWalkwayController.java
  app-external-api/src/main/java/com/dongsan/api/domains/walkway/ReviewController.java
  app-external-api/src/main/java/com/dongsan/api/domains/walkway/WalkwayController.java
  app-external-api/src/main/java/com/dongsan/api/support/controller/HealthController.java
  app-external-api/src/main/java/com/dongsan/api/support/error/ApiErrorCode.java
  app-external-api/src/main/java/com/dongsan/api/support/error/ApiException.java
  app-external-api/src/main/java/com/dongsan/api/support/error/ExceptionAdvice.java
  app-external-api/src/main/java/com/dongsan/api/support/error/SystemErrorCode.java
  app-external-api/src/main/java/com/dongsan/api/support/response/ApiResponse.java
  app-external-api/src/main/java/com/dongsan/api/support/response/ExceptionAdvice.java
  app-external-api/src/main/java/com/dongsan/api/support/response/ValidationError.java
  app-external-api/src/main/java/com/dongsan/api/support/validation/annotation/ExistBookmark.java
  app-external-api/src/main/java/com/dongsan/api/support/validation/annotation/ExistReview.java
  app-external-api/src/main/java/com/dongsan/api/support/validation/annotation/ExistWalkway.java
  app-external-api/src/main/java/com/dongsan/api/support/validation/annotation/NotEmptyWalkwayCourse.java
  app-external-api/src/main/java/com/dongsan/api/support/validation/validator/ExistBookmarkValidator.java
  app-external-api/src/main/java/com/dongsan/api/support/validation/validator/ExistReviewValidator.java
  app-external-api/src/main/java/com/dongsan/api/support/validation/validator/ExistWalkwayValidator.java
  app-external-api/src/main/java/com/dongsan/api/support/validation/validator/NotEmptyCourseValidator.java
  build.gradle
  core-domain/src/main/java/com/dongsan/core/common/annotation/UseCase.java
  core-domain/src/main/java/com/dongsan/core/common/apiResponse/ErrorResponse.java
  core-domain/src/main/java/com/dongsan/core/common/apiResponse/ResponseFactory.java
  core-domain/src/main/java/com/dongsan/core/common/apiResponse/SuccessResponse.java
  core-domain/src/main/java/com/dongsan/core/common/apiResponse/ValidationError.java
  core-domain/src/main/java/com/dongsan/core/common/error/CoreErrorCode.java
  core-domain/src/main/java/com/dongsan/core/common/error/CoreException.java
  core-domain/src/main/java/com/dongsan/core/domains/bookmark/BookmarkService.java
  core-domain/src/main/java/com/dongsan/core/domains/image/ImageService.java
  core-domain/src/main/java/com/dongsan/core/domains/member/MemberService.java
  core-domain/src/main/java/com/dongsan/core/domains/review/ReviewMapper.java
  core-domain/src/main/java/com/dongsan/core/domains/review/ReviewService.java
  core-domain/src/main/java/com/dongsan/core/domains/review/UserReviewService.java
  core-domain/src/main/java/com/dongsan/core/domains/walkway/UserWalkwayUseCase.java
  core-domain/src/main/java/com/dongsan/core/domains/walkway/usecase/HashtagService.java
  core-domain/src/main/java/com/dongsan/core/domains/walkway/usecase/LikedWalkwayService.java
  core-domain/src/main/java/com/dongsan/core/domains/walkway/usecase/WalkwayService.java
  core-domain/src/main/java/com/dongsan/core/support/error/CoreErrorCode.java
  core-domain/src/main/java/com/dongsan/core/support/error/CoreErrorStatus.java
  core-domain/src/main/java/com/dongsan/core/support/error/CoreException.java
  core-domain/src/main/java/com/dongsan/core/support/format/TimeFormat.java
Labels: ✨ Feature

#49 [fix/DB-164]: 토큰 발급 로직 response body로 수정
  app-external-api/src/main/java/com/dongsan/domains/auth/controller/AuthController.java
  app-external-api/src/main/java/com/dongsan/domains/auth/dto/RenewToken.java
  app-external-api/src/main/java/com/dongsan/domains/auth/usecase/AuthUseCase.java
  app-external-api/src/main/java/com/dongsan/domains/dev/controller/DevController.java
  app-external-api/src/main/java/com/dongsan/domains/dev/usecase/DevUseCase.java
Labels: 🐞 Fix
