Repository DongSanOfficial/DongSan-Backend, pull requests merged in 2025-08, with the labels that each got.

#106 [refactor/DB-350]: 같이 산책 API 수정
  dongsan-core/domain-rdb/src/main/java/com/dongsan/domain/domains/cowalk/domain/CowalkPost.java
  dongsan-external-api/src/main/java/com/dongsan/api/domains/cowalk/CowalkPostFacade.java
  dongsan-external-api/src/main/java/com/dongsan/api/domains/cowalk/dto/request/CreateCowalkPostRequest.java
  dongsan-external-api/src/main/java/com/dongsan/api/domains/cowalk/dto/response/CowalkPostDetailResponse.java
Labels: ♻️ Refactor

#109 [fix/DB-357]: 크루 피드가 크루 생성 날짜 이후의 산책 기록만 보여주도록 수정
  dongsan-core/domain-rdb/src/main/java/com/dongsan/domain/domains/walkwayLog/WalkwayLogCoreRepository.java
  dongsan-core/domain-rdb/src/main/java/com/dongsan/domain/domains/walkwayLog/WalkwayLogRdbService.java
  dongsan-core/domain-rdb/src/main/java/com/dongsan/domain/domains/walkwayLog/WalkwayLogRepository.java
  dongsan-external-api/src/main/java/com/dongsan/api/domains/crew/CrewInfoFacade.java
Labels: 🐞 Fix

#110 [feature/DB-328]: 크루 가입 동시성 처리 - 분산 락 도입
  dongsan-core/domain-rdb/src/main/java/com/dongsan/domain/config/P6spyConfig.java
  dongsan-core/domain-redis/src/main/java/com/dongsan/domain/cache/CowalkCacheRepository.java
  dongsan-core/domain-redis/src/main/java/com/dongsan/domain/cache/CrewWalkCacheRepository.java
  dongsan-core/domain-redis/src/main/java/com/dongsan/domain/cache/WalkData.java
  dongsan-core/domain-redis/src/main/java/com/dongsan/domain/domains/cowalk/LockRepository.java
  dongsan-core/domain-redis/src/main/java/com/dongsan/domain/lock/CowalkPostLockService.java
  dongsan-core/domain-redis/src/main/java/com/dongsan/domain/lock/LockRepository.java
  dongsan-core/domain-redis/src/main/java/com/dongsan/domain/lock/LockTransactionExecutor.java
  dongsan-core/domain-redis/src/main/java/com/dongsan/domain/lock/RedisLockService.java
  dongsan-core/domain-redis/src/main/java/com/dongsan/domain/refresh/GetTokenRemaining.java
  dongsan-core/domain-redis/src/main/java/com/dongsan/domain/refresh/TokenCacheRepository.java
  dongsan-core/domain-redis/src/main/java/com/dongsan/domain/refresh/TokenReader.java
  dongsan-core/domain-redis/src/main/java/com/dongsan/domain/refresh/TokenRepository.java
  dongsan-core/domain-redis/src/main/java/com/dongsan/domain/refresh/TokenWriter.java
  dongsan-external-api/build.gradle
  dongsan-external-api/src/main/java/com/dongsan/api/config/SecurityConfig.java
  dongsan-external-api/src/main/java/com/dongsan/api/domains/auth/AuthFilter.java
  dongsan-external-api/src/main/java/com/dongsan/api/domains/auth/AuthService.java
  dongsan-external-api/src/main/java/com/dongsan/api/domains/auth/CustomSuccessHandler.java
  dongsan-external-api/src/main/java/com/dongsan/api/domains/cowalk/CowalkPostFacade.java
  dongsan-external-api/src/main/java/com/dongsan/api/domains/crew/CrewInfoFacade.java
  dongsan-external-api/src/main/java/com/dongsan/api/domains/dev/DevController.java
  dongsan-external-api/src/main/java/com/dongsan/api/domains/dev/DevService.java
  dongsan-external-api/src/main/java/com/dongsan/socket/WalkController.java
  dongsan-external-api/src/test/java/com/dongsan/api/domains/crew/CrewInFoFacadeTest.java
Labels: ✨ Feature

#111 [feature/DB-358]: 산책로 조건 수정
  dongsan-core/domain-rdb/src/main/java/com/dongsan/domain/domains/walkway/domain/WalkwayInfo.java
  dongsan-external-api/src/main/java/com/dongsan/api/domains/walkway/dto/request/UpdateWalkwayRequest.java
Labels: 🐞 Fix

#112 [test/DB-363]: 도메인 객체 테스트 코드 보안
  dongsan-core/domain-rdb/src/main/java/com/dongsan/domain/domains/crew/domain/CrewMemberRole.java
  dongsan-core/domain-rdb/src/main/java/com/dongsan/domain/domains/walkway/domain/MetaWalkwayRating.java
  dongsan-core/domain-rdb/src/main/java/com/dongsan/domain/domains/walkway/domain/WalkwayExposeLevel.java
  dongsan-core/domain-rdb/src/main/java/com/dongsan/domain/domains/walkway/domain/WalkwayInfo.java
  dongsan-core/domain-rdb/src/test/java/com/dongsan/domain/domains/auth/ProviderTest.java
  dongsan-core/domain-rdb/src/test/java/com/dongsan/domain/domains/bookmark/domain/BookmarkTest.java
  dongsan-core/domain-rdb/src/test/java/com/dongsan/domain/domains/bookmark/domain/MarkedWalkwayTest.java
  dongsan-core/domain-rdb/src/test/java/com/dongsan/domain/domains/cowalk/domain/CowalkCommentTest.java
  dongsan-core/domain-rdb/src/test/java/com/dongsan/domain/domains/cowalk/domain/CowalkPostTest.java
  dongsan-core/domain-rdb/src/test/java/com/dongsan/domain/domains/crew/domain/CapacityTest.java
  dongsan-core/domain-rdb/src/test/java/com/dongsan/domain/domains/crew/domain/CapacityTypeTest.java
  dongsan-core/domain-rdb/src/test/java/com/dongsan/domain/domains/crew/domain/CrewAccessPolicyTest.java
  dongsan-core/domain-rdb/src/test/java/com/dongsan/domain/domains/crew/domain/CrewInfoTest.java
  dongsan-core/domain-rdb/src/test/java/com/dongsan/domain/domains/crew/domain/CrewMemberTest.java
  dongsan-core/domain-rdb/src/test/java/com/dongsan/domain/domains/crew/domain/CrewTest.java
  dongsan-core/domain-rdb/src/test/java/com/dongsan/domain/domains/crew/domain/MetaCrewRankingTest.java
  dongsan-core/domain-rdb/src/test/java/com/dongsan/domain/domains/image/ImageTest.java
  dongsan-core/domain-rdb/src/test/java/com/dongsan/domain/domains/member/MemberTest.java
  dongsan-core/domain-rdb/src/test/java/com/dongsan/domain/domains/review/domain/RatingTest.java
  dongsan-core/domain-rdb/src/test/java/com/dongsan/domain/domains/review/domain/ReviewTest.java
  dongsan-core/domain-rdb/src/test/java/com/dongsan/domain/domains/walkway/WalkwaySortTest.java
  dongsan-core/domain-rdb/src/test/java/com/dongsan/domain/domains/walkway/domain/MetaWalkwayLikedTest.java
  dongsan-core/domain-rdb/src/test/java/com/dongsan/domain/domains/walkway/domain/MetaWalkwayRatingTest.java
  dongsan-core/domain-rdb/src/test/java/com/dongsan/domain/domains/walkway/domain/WalkwayInfoTest.java
  dongsan-core/domain-rdb/src/test/java/com/dongsan/domain/domains/walkway/domain/WalkwayTest.java
  dongsan-core/domain-rdb/src/test/java/com/dongsan/domain/domains/walkwayLog/WalkwayLogTest.java
  dongsan-core/domain-rdb/src/test/java/com/dongsan/rdb/domains/review/domain/ReviewTest.java
  dongsan-core/domain-rdb/src/testFixtures/java/fixture/WalkwayGeometryTestBuilder.java
  dongsan-core/domain-rdb/src/testFixtures/java/fixture/WalkwayInfoTestBuilder.java
  dongsan-core/domain-rdb/src/testFixtures/java/fixture/WalkwayTestBuilder.java
  dongsan-external-api/src/main/java/com/dongsan/api/domains/crew/CrewInfoFacade.java
  dongsan-external-api/src/main/java/com/dongsan/api/domains/crew/CrewJoinFacade.java
Labels: ✅ Test, 🐞 Fix

#116 [test/DB-379]: 테스트 속도 개선
  build.gradle
  codecov.yml
  dongsan-core/domain-rdb/src/main/java/com/dongsan/domain/domains/bookmark/infrastructure/MarkedWalkwayJpaRepository.java
  dongsan-core/domain-rdb/src/main/java/com/dongsan/domain/domains/bookmark/infrastructure/dto/MarkedWalkwayParam.java
  dongsan-core/domain-rdb/src/main/java/com/dongsan/domain/domains/crew/domain/CrewMemberRole.java
  dongsan-core/domain-rdb/src/main/java/com/dongsan/domain/domains/crew/domain/CrewRepository.java
  dongsan-core/domain-rdb/src/main/java/com/dongsan/domain/domains/crew/infrastructure/CrewCoreRepository.java
  dongsan-core/domain-rdb/src/main/java/com/dongsan/domain/domains/crew/service/CrewRdbService.java
  dongsan-core/domain-rdb/src/main/java/com/dongsan/domain/domains/walkway/domain/MetaWalkwayLikedRepository.java
  dongsan-core/domain-rdb/src/main/java/com/dongsan/domain/domains/walkway/domain/MetaWalkwayRatingRepository.java
  dongsan-core/domain-rdb/src/main/java/com/dongsan/domain/domains/walkway/infrastructure/MetaWalkwayLikedCoreRepository.java
  dongsan-core/domain-rdb/src/main/java/com/dongsan/domain/domains/walkway/infrastructure/MetaWalkwayLikedJpaRepository.java
  dongsan-core/domain-rdb/src/main/java/com/dongsan/domain/domains/walkway/infrastructure/MetaWalkwayRatingCoreRepository.java
  dongsan-core/domain-rdb/src/main/java/com/dongsan/domain/domains/walkway/infrastructure/MetaWalkwayRatingJpaRepository.java
  dongsan-core/domain-rdb/src/main/java/com/dongsan/domain/domains/walkway/infrastructure/WalkwayJpaRepository.java
  dongsan-core/domain-rdb/src/main/java/com/dongsan/domain/domains/walkway/service/MetaWalkwayLikedRdbService.java
  dongsan-core/domain-rdb/src/main/java/com/dongsan/domain/domains/walkway/service/MetaWalkwayRatingRdbService.java
  dongsan-core/domain-redis/src/main/java/com/dongsan/domain/lock/RedisLockService.java
  dongsan-external-api/src/test/java/com/dongsan/api/domains/crew/CrewInFoFacadeTest.java
  dongsan-external-api/src/test/java/com/dongsan/api/domains/crew/CrewIntegrationTest.java
  dongsan-external-api/src/test/java/com/dongsan/api/support/IntegrationTest.java
  dongsan-external-api/src/test/java/com/dongsan/api/support/factory/CrewFactory.java
Labels: ✅ Test
