Repository DongSanOfficial/DongSan-Backend, pull requests merged in 2025-01, with the labels that each got.

#31 [hotfix/DB-115] : 프론트 배포 도메인 CORS 요청 허용
  app-external-api/src/main/java/com/dongsan/config/SecurityConfig.java
Labels: 🚑 Hotfix

#32 [feature/DB-117]: 산책로 등록 API 수정
  app-external-api/src/main/java/com/dongsan/domains/image/usecase/S3UseCase.java
  app-external-api/src/main/java/com/dongsan/domains/walkway/controller/WalkwayController.java
  app-external-api/src/test/java/com/dongsan/domains/image/usecase/S3UseCaseTest.java
  app-external-api/src/test/java/com/dongsan/domains/walkway/controller/WalkwayControllerTest.java
  core-domain/src/main/java/com/dongsan/domains/image/service/ImageCommandService.java
  core-domain/src/main/java/com/dongsan/domains/image/service/ImageQueryService.java
  core-domain/src/main/java/com/dongsan/domains/image/usecase/ImageUseCase.java
  core-domain/src/main/java/com/dongsan/domains/walkway/dto/request/CreateWalkwayRequest.java
  core-domain/src/main/java/com/dongsan/domains/walkway/dto/request/UpdateWalkwayRequest.java
  core-domain/src/main/java/com/dongsan/domains/walkway/dto/response/CreateWalkwayCourseImageRequest.java
  core-domain/src/main/java/com/dongsan/domains/walkway/dto/response/CreateWalkwayResponse.java
  core-domain/src/main/java/com/dongsan/domains/walkway/dto/response/GetWalkwayWithLikedResponse.java
  core-domain/src/main/java/com/dongsan/domains/walkway/mapper/WalkwayMapper.java
  core-domain/src/main/java/com/dongsan/domains/walkway/service/HashtagQueryService.java
  core-domain/src/main/java/com/dongsan/domains/walkway/service/WalkwayQueryService.java
  core-domain/src/main/java/com/dongsan/domains/walkway/usecase/HashtagUseCase.java
  core-domain/src/main/java/com/dongsan/domains/walkway/usecase/WalkwayReviewUseCase.java
  core-domain/src/main/java/com/dongsan/domains/walkway/usecase/WalkwayUseCase.java
  core-domain/src/test/java/com/dongsan/domains/image/service/ImageCommandServiceTest.java
  core-domain/src/test/java/com/dongsan/domains/image/service/ImageQueryServiceTest.java
  core-domain/src/test/java/com/dongsan/domains/image/usecase/ImageUseCaseTest.java
  core-domain/src/test/java/com/dongsan/domains/walkway/service/HashtagQueryServiceTest.java
  core-domain/src/test/java/com/dongsan/domains/walkway/service/WalkwayCommandServiceTest.java
  core-domain/src/test/java/com/dongsan/domains/walkway/service/WalkwayQueryServiceTest.java
  core-domain/src/test/java/com/dongsan/domains/walkway/usecase/HashtagUseCaseTest.java
  core-domain/src/test/java/com/dongsan/domains/walkway/usecase/WalkwayReviewUseCaseTest.java
  core-domain/src/test/java/com/dongsan/domains/walkway/usecase/WalkwayUseCaseTest.java
  infrastructure/storage-rdb/src/main/java/com/dongsan/common/error/code/ImageErrorCode.java
  infrastructure/storage-rdb/src/main/java/com/dongsan/common/error/code/WalkwayErrorCode.java
  infrastructure/storage-rdb/src/main/java/com/dongsan/domains/hashtag/repository/HashtagRepository.java
  infrastructure/storage-rdb/src/main/java/com/dongsan/domains/image/entity/Image.java
  infrastructure/storage-rdb/src/main/java/com/dongsan/domains/image/repository/ImageRepository.java
  infrastructure/storage-rdb/src/main/java/com/dongsan/domains/walkway/dto/SearchWalkwayRating.java
  infrastructure/storage-rdb/src/main/java/com/dongsan/domains/walkway/entity/Walkway.java
  infrastructure/storage-rdb/src/main/java/com/dongsan/domains/walkway/repository/WalkwayQueryDSLRepository.java
  infrastructure/storage-rdb/src/test/java/com/dongsan/domains/walkway/repository/WalkwayQueryDSLRepositoryTest.java
  infrastructure/storage-rdb/src/testFixtures/java/fixture/ImageFixture.java
Labels: ♻️ Refactor, 🐞 Fix, ✨ Feature

#33 [feature/DB-121]: 산책로 검색 수정
  app-external-api/src/main/java/com/dongsan/domains/walkway/controller/ReviewController.java
  app-external-api/src/main/java/com/dongsan/domains/walkway/controller/WalkwayController.java
  app-external-api/src/test/java/com/dongsan/domains/walkway/controller/WalkwayControllerTest.java
  core-domain/src/main/java/com/dongsan/domains/walkway/dto/request/CreateWalkwayRequest.java
  core-domain/src/main/java/com/dongsan/domains/walkway/dto/response/SearchWalkwayResponse.java
  core-domain/src/main/java/com/dongsan/domains/walkway/enums/Sort.java
  core-domain/src/main/java/com/dongsan/domains/walkway/service/WalkwayQueryService.java
  core-domain/src/main/java/com/dongsan/domains/walkway/service/factory/SearchWalkwayServiceFactory.java
  core-domain/src/main/java/com/dongsan/domains/walkway/service/search/SearchLikedWalkwayService.java
  core-domain/src/main/java/com/dongsan/domains/walkway/service/search/SearchRatingWalkwayService.java
  core-domain/src/main/java/com/dongsan/domains/walkway/service/search/SearchWalkwayService.java
  core-domain/src/main/java/com/dongsan/domains/walkway/usecase/WalkwayUseCase.java
  core-domain/src/test/java/com/dongsan/domains/walkway/service/WalkwayQueryServiceTest.java
  core-domain/src/test/java/com/dongsan/domains/walkway/service/factory/SearchWalkwayServiceFactoryTest.java
  core-domain/src/test/java/com/dongsan/domains/walkway/service/search/SearchLikedWalkwayServiceTest.java
  core-domain/src/test/java/com/dongsan/domains/walkway/service/search/SearchRatingWalkwayServiceTest.java
  core-domain/src/test/java/com/dongsan/domains/walkway/usecase/WalkwayUseCaseTest.java
  infrastructure/storage-rdb/src/main/java/com/dongsan/common/error/code/WalkwayErrorCode.java
  infrastructure/storage-rdb/src/main/java/com/dongsan/config/QueryDSLConfig.java
  infrastructure/storage-rdb/src/main/java/com/dongsan/domains/walkway/dto/request/SearchWalkwayQuery.java
  infrastructure/storage-rdb/src/main/java/com/dongsan/domains/walkway/dto/response/SearchWalkwayResult.java
  infrastructure/storage-rdb/src/main/java/com/dongsan/domains/walkway/repository/WalkwayQueryDSLRepository.java
Labels: ✅ Test, ✨ Feature

#34 [refactor/DB-124]: 북마크 상세 조회, 사용자 산책로&리뷰 조회 API 수정
  app-external-api/src/main/java/com/dongsan/common/controller/HealthController.java
  app-external-api/src/main/java/com/dongsan/config/SwaggerConfig.java
  app-external-api/src/main/java/com/dongsan/domains/bookmark/controller/BookmarkController.java
  app-external-api/src/main/java/com/dongsan/domains/dev/controller/DevController.java
  app-external-api/src/main/java/com/dongsan/domains/user/controller/UserProfileController.java
  app-external-api/src/main/java/com/dongsan/domains/user/controller/UserReviewController.java
  app-external-api/src/main/java/com/dongsan/domains/user/controller/UserWalkwayController.java
  app-external-api/src/main/java/com/dongsan/domains/walkway/controller/LikedWalkwayController.java
  app-external-api/src/main/java/com/dongsan/domains/walkway/controller/ReviewController.java
  app-external-api/src/main/java/com/dongsan/domains/walkway/controller/WalkwayController.java
  app-external-api/src/test/java/com/dongsan/domains/bookmark/controller/BookmarkControllerTest.java
  app-external-api/src/test/java/com/dongsan/domains/user/controller/UserReviewControllerTest.java
  app-external-api/src/test/java/com/dongsan/domains/user/controller/UserWalkwayControllerTest.java
  build.gradle
  container/database/docker-compose.yml
  core-domain/src/main/java/com/dongsan/domains/bookmark/dto/param/GetBookmarkDetailParam.java
  core-domain/src/main/java/com/dongsan/domains/bookmark/dto/response/GetBookmarkDetailResponse.java
  core-domain/src/main/java/com/dongsan/domains/bookmark/mapper/BookmarkMapper.java
  core-domain/src/main/java/com/dongsan/domains/bookmark/usecase/BookmarkUseCase.java
  core-domain/src/main/java/com/dongsan/domains/user/mapper/UserReviewMapper.java
  core-domain/src/main/java/com/dongsan/domains/user/response/GetReviewResponse.java
  core-domain/src/main/java/com/dongsan/domains/user/response/WalkwayListResponse.java
  core-domain/src/main/java/com/dongsan/domains/user/response/WalkwayResponse.java
  core-domain/src/main/java/com/dongsan/domains/user/usecase/UserReviewUseCase.java
  core-domain/src/main/java/com/dongsan/domains/user/usecase/UserWalkwayUseCase.java
  core-domain/src/main/java/com/dongsan/domains/walkway/service/LikedWalkwayQueryService.java
  core-domain/src/main/java/com/dongsan/domains/walkway/service/ReviewQueryService.java
  core-domain/src/main/java/com/dongsan/domains/walkway/service/WalkwayQueryService.java
  core-domain/src/test/java/com/dongsan/domains/bookmark/usecase/BookmarkUseCaseTest.java
  core-domain/src/test/java/com/dongsan/domains/user/usecase/UserReviewUseCaseTest.java
  core-domain/src/test/java/com/dongsan/domains/user/usecase/UserWalkwayUseCaseTest.java
  core-domain/src/test/java/com/dongsan/domains/walkway/service/LikedWalkwayQueryServiceTest.java
  core-domain/src/test/java/com/dongsan/domains/walkway/service/ReviewQueryServiceTest.java
  core-domain/src/test/java/com/dongsan/domains/walkway/service/WalkwayQueryServiceTest.java
  infrastructure/storage-rdb/src/main/java/com/dongsan/domains/bookmark/repository/MarkedWalkwayQueryDSLRepository.java
  infrastructure/storage-rdb/src/main/java/com/dongsan/domains/review/repository/ReviewQueryDSLRepository.java
  infrastructure/storage-rdb/src/main/java/com/dongsan/domains/walkway/repository/LikedWalkwayQueryDSLRepository.java
  infrastructure/storage-rdb/src/test/java/com/dongsan/domains/bookmark/repository/MarkedWalkwayQueryDSLRepositoryTest.java
  infrastructure/storage-rdb/src/test/java/com/dongsan/domains/review/repository/ReviewQueryDSLRepositoryTest.java
  infrastructure/storage-rdb/src/test/java/com/dongsan/domains/walkway/repository/LikedWalkwayQueryDSLRepositoryTest.java
  infrastructure/storage-rdb/src/testFixtures/java/fixture/WalkwayFixture.java
Labels: 📃 Docs, ♻️ Refactor, 🐞 Fix

#35 [feature/DB-125]: 리뷰 API 수정
  app-external-api/src/main/java/com/dongsan/domains/user/controller/UserProfileController.java
  app-external-api/src/main/java/com/dongsan/domains/walkway/controller/ReviewController.java
  app-external-api/src/main/java/com/dongsan/domains/walkway/controller/WalkwayController.java
  app-external-api/src/test/java/com/dongsan/domains/user/controller/UserProfileControllerTest.java
  app-external-api/src/test/java/com/dongsan/domains/walkway/controller/ReviewControllerTest.java
  app-external-api/src/test/java/com/dongsan/domains/walkway/controller/WalkwayControllerTest.java
  core-domain/src/main/java/com/dongsan/domains/bookmark/dto/response/BookmarksWithMarkedWalkwayResponse.java
  core-domain/src/main/java/com/dongsan/domains/bookmark/mapper/BookmarksWithMarkedWalkwayMapper.java
  core-domain/src/main/java/com/dongsan/domains/bookmark/service/BookmarkQueryService.java
  core-domain/src/main/java/com/dongsan/domains/bookmark/usecase/BookmarkUseCase.java
  core-domain/src/main/java/com/dongsan/domains/user/mapper/UserBookmarkMapper.java
  core-domain/src/main/java/com/dongsan/domains/user/response/GetBookmarksResponse.java
  core-domain/src/main/java/com/dongsan/domains/user/usecase/UserProfileUseCase.java
  core-domain/src/main/java/com/dongsan/domains/walkway/dto/request/CreateReviewRequest.java
  core-domain/src/main/java/com/dongsan/domains/walkway/dto/response/GetWalkwayReviewsResponse.java
  core-domain/src/main/java/com/dongsan/domains/walkway/enums/ReviewSort.java
  core-domain/src/main/java/com/dongsan/domains/walkway/enums/WalkwaySort.java
  core-domain/src/main/java/com/dongsan/domains/walkway/mapper/ReviewMapper.java
  core-domain/src/main/java/com/dongsan/domains/walkway/service/ReviewQueryService.java
  core-domain/src/main/java/com/dongsan/domains/walkway/service/WalkwayQueryService.java
  core-domain/src/main/java/com/dongsan/domains/walkway/service/factory/GetReviewsServiceFactory.java
  core-domain/src/main/java/com/dongsan/domains/walkway/service/factory/SearchWalkwayServiceFactory.java
  core-domain/src/main/java/com/dongsan/domains/walkway/service/search/review/GetLatestReviewsService.java
  core-domain/src/main/java/com/dongsan/domains/walkway/service/search/review/GetRatingReviewsService.java
  core-domain/src/main/java/com/dongsan/domains/walkway/service/search/review/GetReviewsService.java
  core-domain/src/main/java/com/dongsan/domains/walkway/service/search/walkway/SearchLikedWalkwayService.java
  core-domain/src/main/java/com/dongsan/domains/walkway/service/search/walkway/SearchRatingWalkwayService.java
  core-domain/src/main/java/com/dongsan/domains/walkway/service/search/walkway/SearchWalkwayService.java
  core-domain/src/main/java/com/dongsan/domains/walkway/usecase/WalkwayReviewUseCase.java
  core-domain/src/main/java/com/dongsan/domains/walkway/usecase/WalkwayUseCase.java
  core-domain/src/test/java/com/dongsan/domains/bookmark/service/BookmarkQueryServiceTest.java
  core-domain/src/test/java/com/dongsan/domains/bookmark/usecase/BookmarkUseCaseTest.java
  core-domain/src/test/java/com/dongsan/domains/user/usecase/UserProfileUseCaseTest.java
  core-domain/src/test/java/com/dongsan/domains/walkway/service/ReviewQueryServiceTest.java
  core-domain/src/test/java/com/dongsan/domains/walkway/service/WalkwayQueryServiceTest.java
  core-domain/src/test/java/com/dongsan/domains/walkway/service/factory/GetReviewsServiceFactoryTest.java
  core-domain/src/test/java/com/dongsan/domains/walkway/service/factory/SearchWalkwayServiceFactoryTest.java
  core-domain/src/test/java/com/dongsan/domains/walkway/service/search/review/GetLatestReviewsServiceTest.java
  core-domain/src/test/java/com/dongsan/domains/walkway/service/search/review/GetRatingReviewsServiceTest.java
  core-domain/src/test/java/com/dongsan/domains/walkway/service/search/walkway/SearchLikedWalkwayServiceTest.java
  core-domain/src/test/java/com/dongsan/domains/walkway/service/search/walkway/SearchRatingWalkwayServiceTest.java
  core-domain/src/test/java/com/dongsan/domains/walkway/usecase/WalkwayReviewUseCaseTest.java
  core-domain/src/test/java/com/dongsan/domains/walkway/usecase/WalkwayUseCaseTest.java
  infrastructure/storage-rdb/src/main/java/com/dongsan/common/error/code/WalkwayErrorCode.java
  infrastructure/storage-rdb/src/main/java/com/dongsan/domains/bookmark/repository/BookmarkQueryDSLRepository.java
  infrastructure/storage-rdb/src/main/java/com/dongsan/domains/review/dto/RatingCount.java
  infrastructure/storage-rdb/src/main/java/com/dongsan/domains/review/entity/Review.java
  infrastructure/storage-rdb/src/main/java/com/dongsan/domains/review/repository/ReviewQueryDSLRepository.java
  infrastructure/storage-rdb/src/main/java/com/dongsan/domains/walkway/entity/Walkway.java
  infrastructure/storage-rdb/src/main/java/com/dongsan/domains/walkway/repository/WalkwayQueryDSLRepository.java
  infrastructure/storage-rdb/src/test/java/com/dongsan/domains/bookmark/repository/BookmarkQueryDSLRepositoryTest.java
  infrastructure/storage-rdb/src/test/java/com/dongsan/domains/review/repository/ReviewQueryDSLRepositoryTest.java
  infrastructure/storage-rdb/src/testFixtures/java/fixture/ReviewFixture.java
Labels: ♻️ Refactor

#36 [refactor/DB-134]: 산책로 API 좌표 위도, 경도 순으로 수정
  app-external-api/src/test/java/com/dongsan/domains/walkway/controller/WalkwayControllerTest.java
  core-domain/src/main/java/com/dongsan/domains/walkway/dto/WalkwayCoordinate.java
  core-domain/src/main/java/com/dongsan/domains/walkway/dto/request/CreateWalkwayRequest.java
  core-domain/src/main/java/com/dongsan/domains/walkway/dto/response/GetWalkwaySearchResponse.java
  core-domain/src/main/java/com/dongsan/domains/walkway/dto/response/GetWalkwayWithLikedResponse.java
  core-domain/src/main/java/com/dongsan/domains/walkway/dto/response/SearchWalkwayResponse.java
  core-domain/src/main/java/com/dongsan/domains/walkway/mapper/LineStringMapper.java
  core-domain/src/test/java/com/dongsan/domains/walkway/usecase/WalkwayUseCaseTest.java
Labels: ♻️ Refactor
