Repository DongSanOfficial/DongSan-Backend, pull requests merged in 2025-03, with the labels that each got.

#61 [fix/DB-206]: API 에러 수정
  app-external-api/src/main/java/com/dongsan/api/domains/review/GetWalkwayRatingResponse.java
  app-external-api/src/main/java/com/dongsan/api/domains/walkway/WalkwayController.java
  app-external-api/src/main/java/com/dongsan/api/domains/walkway/dto/response/BookmarksWithMarkedWalkwayResponse.java
  app-external-api/src/test/java/com/dongsan/api/domains/walkway/WalkwayControllerTest.java
  core-domain/src/main/java/com/dongsan/core/domains/walkway/WalkwayService.java
  core-domain/src/test/java/com/dongsan/core/domains/walkway/WalkwayServiceTest.java
  infrastructure/storage-rdb/src/main/java/com/dongsan/rdb/domains/walkway/LikedWalkwayQueryDSLRepository.java
Labels: 🐞 Fix

#63 [test/DB-211]: 산책로 북마크 목록 테스트 수정
  app-external-api/src/test/java/com/dongsan/api/domains/walkway/WalkwayControllerTest.java
Labels: ✅ Test

#65 [refactor/DB-214]: 리뷰 별점 Enum 수정, 산책로 좋아요 수정
  app-external-api/src/main/java/com/dongsan/api/domains/review/CreateReviewRequest.java
  app-external-api/src/main/java/com/dongsan/api/domains/review/MyReviewResponse.java
  app-external-api/src/main/java/com/dongsan/api/domains/review/ReviewController.java
  app-external-api/src/main/java/com/dongsan/api/domains/review/WalkwayRatingResponse.java
  app-external-api/src/main/java/com/dongsan/api/domains/review/WalkwayReviewsResponse.java
  app-external-api/src/main/java/com/dongsan/api/domains/walkway/LikedWalkwayController.java
  app-external-api/src/main/java/com/dongsan/api/domains/walkway/LineStringMapper.java
  app-external-api/src/main/java/com/dongsan/api/domains/walkway/WalkwayController.java
  app-external-api/src/main/java/com/dongsan/api/domains/walkway/dto/request/CreateWalkwayRequest.java
  app-external-api/src/main/java/com/dongsan/api/domains/walkway/dto/request/UpdateWalkwayRequest.java
  app-external-api/src/main/java/com/dongsan/api/domains/walkway/dto/response/WalkwayDetailResponse.java
  app-external-api/src/main/java/com/dongsan/api/domains/walkway/mapper/WalkwayMapper.java
  app-external-api/src/main/java/com/dongsan/api/support/validation/annotation/ValidRating.java
  app-external-api/src/main/java/com/dongsan/api/support/validation/validator/RatingValidator.java
  app-external-api/src/test/java/com/dongsan/api/domains/review/ReviewControllerTest.java
  app-external-api/src/test/java/com/dongsan/api/domains/walkway/WalkwayControllerTest.java
  core-domain/src/main/java/com/dongsan/core/domains/review/CreateReview.java
  core-domain/src/main/java/com/dongsan/core/domains/review/GetRatingReviews.java
  core-domain/src/main/java/com/dongsan/core/domains/review/Rating.java
  core-domain/src/main/java/com/dongsan/core/domains/review/RatingCalculator.java
  core-domain/src/main/java/com/dongsan/core/domains/review/Review.java
  core-domain/src/main/java/com/dongsan/core/domains/review/ReviewReader.java
  core-domain/src/main/java/com/dongsan/core/domains/review/ReviewRepository.java
  core-domain/src/main/java/com/dongsan/core/domains/review/ReviewService.java
  core-domain/src/main/java/com/dongsan/core/domains/walkway/WalkwayReader.java
  core-domain/src/main/java/com/dongsan/core/domains/walkway/WalkwayRepository.java
  core-domain/src/main/java/com/dongsan/core/domains/walkway/WalkwayService.java
  core-domain/src/main/java/com/dongsan/core/support/error/CoreErrorCode.java
  core-domain/src/test/java/com/dongsan/core/domains/review/ReviewReaderTest.java
  core-domain/src/test/java/com/dongsan/core/domains/review/ReviewServiceTest.java
  core-domain/src/test/java/com/dongsan/core/domains/walkway/WalkwayReaderTest.java
  core-domain/src/test/java/com/dongsan/core/domains/walkway/WalkwayServiceTest.java
  core-domain/src/testFixtures/java/review/ReviewFixture.java
  infrastructure/storage-rdb/src/main/java/com/dongsan/rdb/domains/review/RatingCount.java
  infrastructure/storage-rdb/src/main/java/com/dongsan/rdb/domains/review/ReviewCoreRepository.java
  infrastructure/storage-rdb/src/main/java/com/dongsan/rdb/domains/review/ReviewEntity.java
  infrastructure/storage-rdb/src/main/java/com/dongsan/rdb/domains/walkway/WalkwayCoreJpaRepository.java
  infrastructure/storage-rdb/src/main/java/com/dongsan/rdb/domains/walkway/WalkwayHistoryQueryDSLRepository.java
  infrastructure/storage-rdb/src/test/java/com/dongsan/rdb/domains/review/ReviewCoreRepositoryTest.java
  infrastructure/storage-rdb/src/test/java/com/dongsan/rdb/domains/walkway/WalkwayCoreJpaRepositoryTest.java
  infrastructure/storage-rdb/src/test/java/com/dongsan/rdb/domains/walkway/WalkwayHistoryQueryDSLRepositoryTest.java
  infrastructure/storage-rdb/src/testFixtures/java/fixture/ReviewEntityFixture.java
Labels: ♻️ Refactor, ✨ Feature

#66 [fix/DB-224]: java.lang.UnsupportedOperationException 예외 수정
  app-external-api/src/main/java/com/dongsan/api/domains/walkway/UserWalkwayController.java
  app-external-api/src/main/java/com/dongsan/api/domains/walkway/WalkwayController.java
  app-external-api/src/main/java/com/dongsan/api/domains/walkway/dto/response/GetWalkwayHistoriesResponse.java
  app-external-api/src/test/java/com/dongsan/api/domains/walkway/UserWalkwayControllerTest.java
  app-external-api/src/test/java/com/dongsan/api/domains/walkway/WalkwayControllerTest.java
  core-domain/src/main/java/com/dongsan/core/domains/walkway/WalkwayService.java
  core-domain/src/test/java/com/dongsan/core/domains/walkway/WalkwayServiceTest.java
Labels: ✅ Test, 🐞 Fix

#69 [feature/DB-230]: 산책로 삭제 API
  app-external-api/src/main/java/com/dongsan/api/domains/walkway/WalkwayController.java
  app-external-api/src/test/java/com/dongsan/api/domains/walkway/WalkwayControllerTest.java
  core-domain/src/main/java/com/dongsan/core/domains/walkway/WalkwayRepository.java
  core-domain/src/main/java/com/dongsan/core/domains/walkway/WalkwayService.java
  core-domain/src/main/java/com/dongsan/core/domains/walkway/WalkwayWriter.java
  core-domain/src/test/java/com/dongsan/core/domains/walkway/WalkwayServiceTest.java
  core-domain/src/test/java/com/dongsan/core/domains/walkway/WalkwayWriterTest.java
  infrastructure/storage-rdb/src/main/java/com/dongsan/rdb/domains/bookmark/MarkedWalkwayJpaRepository.java
  infrastructure/storage-rdb/src/main/java/com/dongsan/rdb/domains/review/ReviewJpaRepository.java
  infrastructure/storage-rdb/src/main/java/com/dongsan/rdb/domains/walkway/LikedWalkwayJpaRepository.java
  infrastructure/storage-rdb/src/main/java/com/dongsan/rdb/domains/walkway/WalkwayCoreRepository.java
  infrastructure/storage-rdb/src/main/java/com/dongsan/rdb/domains/walkway/WalkwayHistoryJpaRepository.java
  infrastructure/storage-rdb/src/test/java/com/dongsan/rdb/domains/walkway/WalkwayCoreRepositoryTest.java
Labels: ✨ Feature

#71 [fix/DB-237]: CD 스크립트, Dockerfile 수정
  .github/workflows/cd.yml
  dongsan-external-api/Dockerfile
Labels: 🐞 Fix
