Repository DongSanOfficial/DongSan-Backend, pull requests merged in 2025-07, with the labels that each got.

#99 [infra/DB-336]: pinpoint 연동을 위해 cd 스트립트 수정
  .github/workflows/cd.yml
  dongsan-external-api/Dockerfile
Labels: ⚙ Infra

#100 [feature/DB-377]: 같이 산책하기 - 종료 시간 추가
  dongsan-core/domain-rdb/src/main/java/com/dongsan/domain/domains/cowalk/CreateCowalkPostCommand.java
  dongsan-core/domain-rdb/src/main/java/com/dongsan/domain/domains/cowalk/domain/CowalkPost.java
  dongsan-core/domain-rdb/src/main/java/com/dongsan/domain/domains/cowalk/domain/CowalkPostRepository.java
  dongsan-core/domain-rdb/src/main/java/com/dongsan/domain/domains/cowalk/infrastructure/CowalkPostCoreRepository.java
  dongsan-core/domain-rdb/src/main/java/com/dongsan/domain/domains/cowalk/service/CowalkPostRdbService.java
  dongsan-core/domain-rdb/src/main/java/com/dongsan/domain/domains/walkway/domain/WalkwayInfo.java
  dongsan-core/domain-rdb/src/main/java/com/dongsan/domain/support/error/CoreErrorCode.java
  dongsan-core/domain-rdb/src/test/java/com/dongsan/domain/domains/cowalk/domain/CowalkPostTest.java
  dongsan-external-api/src/main/java/com/dongsan/api/domains/cowalk/dto/request/CreateCowalkPostRequest.java
  dongsan-external-api/src/main/java/com/dongsan/api/domains/cowalk/dto/response/GetMyCowalkResponse.java
  dongsan-external-api/src/main/java/com/dongsan/api/domains/crew/CrewInfoFacade.java
  dongsan-external-api/src/test/java/com/dongsan/api/domains/cowalk/CowalkPostFacadeTest.java
Labels: 🐞 Fix, ✨ Feature

#103 [feature/DB-344]: 가입한 크루 아이디 조회 API
  dongsan-core/domain-rdb/src/main/java/com/dongsan/domain/domains/crew/domain/CrewRepository.java
  dongsan-core/domain-rdb/src/main/java/com/dongsan/domain/domains/crew/infrastructure/CrewCoreRepository.java
  dongsan-core/domain-rdb/src/main/java/com/dongsan/domain/domains/crew/service/CrewRdbService.java
  dongsan-external-api/src/main/java/com/dongsan/api/domains/crew/CrewInfoFacade.java
  dongsan-external-api/src/main/java/com/dongsan/api/domains/crew/MyCrewInfoController.java
  dongsan-external-api/src/main/java/com/dongsan/api/domains/crew/dto/response/GetMyCrewIdsResponse.java
Labels: ✨ Feature

#105 [fix/DB-349]: DTO 수정 및 테이블 필드 매핑 수정
  dongsan-core/domain-rdb/src/main/java/com/dongsan/domain/domains/walkway/domain/WalkwayInfo.java
  dongsan-core/domain-rdb/src/main/java/com/dongsan/domain/domains/walkway/service/WalkwayRdbService.java
  dongsan-external-api/src/main/java/com/dongsan/api/domains/walkway/dto/request/CreateWalkwayRequest.java
  dongsan-external-api/src/main/java/com/dongsan/api/domains/walkway/dto/request/UpdateWalkwayRequest.java
Labels: 🐞 Fix
