Repository DongSanOfficial/DongSan-Backend, pull requests merged in 2025-06, with the labels that each got.

#85 [feature/DB-286]: 같이산책 생성, 조회, 참여 API
  dongsan-core/domain-rdb/src/main/java/com/dongsan/domain/domains/cowalk/CreateCowalkPostCommand.java
  dongsan-core/domain-rdb/src/main/java/com/dongsan/domain/domains/cowalk/domain/CapacityType.java
  dongsan-core/domain-rdb/src/main/java/com/dongsan/domain/domains/cowalk/domain/CowalkComment.java
  dongsan-core/domain-rdb/src/main/java/com/dongsan/domain/domains/cowalk/domain/CowalkCommentRepository.java
  dongsan-core/domain-rdb/src/main/java/com/dongsan/domain/domains/cowalk/domain/CowalkParticipant.java
  dongsan-core/domain-rdb/src/main/java/com/dongsan/domain/domains/cowalk/domain/CowalkParticipantRepository.java
  dongsan-core/domain-rdb/src/main/java/com/dongsan/domain/domains/cowalk/domain/CowalkPost.java
  dongsan-core/domain-rdb/src/main/java/com/dongsan/domain/domains/cowalk/domain/CowalkPostRepository.java
  dongsan-core/domain-rdb/src/main/java/com/dongsan/domain/domains/cowalk/infrastructure/CowalkCommentCoreRepository.java
  dongsan-core/domain-rdb/src/main/java/com/dongsan/domain/domains/cowalk/infrastructure/CowalkCommentJpaRepository.java
  dongsan-core/domain-rdb/src/main/java/com/dongsan/domain/domains/cowalk/infrastructure/CowalkParticipantCoreRepository.java
  dongsan-core/domain-rdb/src/main/java/com/dongsan/domain/domains/cowalk/infrastructure/CowalkParticipantJpaRepository.java
  dongsan-core/domain-rdb/src/main/java/com/dongsan/domain/domains/cowalk/infrastructure/CowalkPostCoreRepository.java
  dongsan-core/domain-rdb/src/main/java/com/dongsan/domain/domains/cowalk/infrastructure/CowalkPostJpaRepository.java
  dongsan-core/domain-rdb/src/main/java/com/dongsan/domain/domains/cowalk/service/CowalkCommentRdbService.java
  dongsan-core/domain-rdb/src/main/java/com/dongsan/domain/domains/cowalk/service/CowalkParticipantRdbService.java
  dongsan-core/domain-rdb/src/main/java/com/dongsan/domain/domains/cowalk/service/CowalkPostRdbService.java
  dongsan-core/domain-rdb/src/main/java/com/dongsan/domain/domains/crew/service/CrewMemberRdbService.java
  dongsan-core/domain-rdb/src/main/java/com/dongsan/domain/domains/member/MemberCoreRepository.java
  dongsan-core/domain-rdb/src/main/java/com/dongsan/domain/domains/member/MemberJpaRepository.java
  dongsan-core/domain-rdb/src/main/java/com/dongsan/domain/domains/member/MemberRepository.java
  dongsan-core/domain-rdb/src/main/java/com/dongsan/domain/domains/member/MemberService.java
  dongsan-core/domain-rdb/src/main/java/com/dongsan/domain/support/error/CoreErrorCode.java
  dongsan-core/domain-rdb/src/test/java/com/dongsan/domain/domains/cowalk/domain/CowalkPostTest.java
  dongsan-core/domain-redis/build.gradle
  dongsan-core/domain-redis/src/main/java/com/dongsan/domain/domains/cowalk/CowalkPostLockService.java
  dongsan-core/domain-redis/src/main/java/com/dongsan/domain/domains/cowalk/LockRepository.java
  dongsan-external-api/src/main/java/com/dongsan/api/domains/cowalk/CowalkPostController.java
  dongsan-external-api/src/main/java/com/dongsan/api/domains/cowalk/CowalkPostFacade.java
  dongsan-external-api/src/main/java/com/dongsan/api/domains/cowalk/dto/request/CreateCowalkPostRequest.java
  dongsan-external-api/src/main/java/com/dongsan/api/domains/cowalk/dto/response/CowalkPostDetailResponse.java
  dongsan-external-api/src/main/java/com/dongsan/api/domains/cowalk/dto/response/CowalkPostsResponse.java
  dongsan-external-api/src/main/java/com/dongsan/api/domains/cowalk/dto/response/CreateCowalkPostResponse.java
  dongsan-external-api/src/main/java/com/dongsan/api/domains/cowalk/dto/response/JoinCowalkParticipantResponse.java
  dongsan-external-api/src/test/java/com/dongsan/api/domains/cowalk/CowalkPostFacadeTest.java
  dongsan-external-api/src/test/java/com/dongsan/api/support/IntegrationTest.java
Labels: ✨ Feature

#87 [feature/DB-295]: 같이 산책 댓글 API 개발
  dongsan-core/domain-rdb/src/main/java/com/dongsan/domain/domains/cowalk/domain/CowalkComment.java
  dongsan-core/domain-rdb/src/main/java/com/dongsan/domain/domains/cowalk/domain/CowalkCommentRepository.java
  dongsan-core/domain-rdb/src/main/java/com/dongsan/domain/domains/cowalk/infrastructure/CowalkCommentCoreRepository.java
  dongsan-core/domain-rdb/src/main/java/com/dongsan/domain/domains/cowalk/service/CowalkCommentRdbService.java
  dongsan-core/domain-rdb/src/main/java/com/dongsan/domain/domains/cowalk/service/CowalkParticipantRdbService.java
  dongsan-core/domain-rdb/src/main/java/com/dongsan/domain/domains/cowalk/service/CowalkPostRdbService.java
  dongsan-core/domain-rdb/src/main/java/com/dongsan/domain/support/error/CoreErrorCode.java
  dongsan-external-api/src/main/java/com/dongsan/api/domains/cowalk/CowalkPostController.java
  dongsan-external-api/src/main/java/com/dongsan/api/domains/cowalk/CowalkPostFacade.java
  dongsan-external-api/src/main/java/com/dongsan/api/domains/cowalk/dto/request/CreateCowalkCommentRequest.java
  dongsan-external-api/src/main/java/com/dongsan/api/domains/cowalk/dto/response/CowalkCommentResponse.java
  dongsan-external-api/src/main/java/com/dongsan/api/domains/cowalk/dto/response/CreateCowalkCommentResponse.java
Labels: ✨ Feature

#89 [feature/DB-298]: 크루 조회 API 개발
  dongsan-core/domain-rdb/src/main/java/com/dongsan/domain/domains/crew/domain/CrewMember.java
  dongsan-core/domain-rdb/src/main/java/com/dongsan/domain/domains/crew/domain/CrewMemberRepository.java
  dongsan-core/domain-rdb/src/main/java/com/dongsan/domain/domains/crew/domain/CrewRepository.java
  dongsan-core/domain-rdb/src/main/java/com/dongsan/domain/domains/crew/domain/MetaCrewRanking.java
  dongsan-core/domain-rdb/src/main/java/com/dongsan/domain/domains/crew/infrastructure/CrewCoreRepository.java
  dongsan-core/domain-rdb/src/main/java/com/dongsan/domain/domains/crew/infrastructure/CrewMemberCoreRepository.java
  dongsan-core/domain-rdb/src/main/java/com/dongsan/domain/domains/crew/infrastructure/MetaCrewRankingJpaRepository.java
  dongsan-core/domain-rdb/src/main/java/com/dongsan/domain/domains/crew/infrastructure/MetaCrewRankingScheduledRepository.java
  dongsan-core/domain-rdb/src/main/java/com/dongsan/domain/domains/crew/service/CrewMemberRdbService.java
  dongsan-core/domain-rdb/src/main/java/com/dongsan/domain/domains/crew/service/CrewRdbService.java
  dongsan-external-api/src/main/java/com/dongsan/ExternalApiApplication.java
  dongsan-external-api/src/main/java/com/dongsan/api/domains/crew/CrewInfoController.java
  dongsan-external-api/src/main/java/com/dongsan/api/domains/crew/CrewInfoFacade.java
  dongsan-external-api/src/main/java/com/dongsan/api/domains/crew/MyCrewInfoController.java
  dongsan-external-api/src/main/java/com/dongsan/api/domains/crew/dto/request/CreateUpdateCrewRequest.java
  dongsan-external-api/src/main/java/com/dongsan/api/domains/crew/dto/response/GetCrewsResponse.java
  dongsan-external-api/src/main/java/com/dongsan/api/domains/walkway/dto/request/CreateWalkwayRequest.java
Labels: ♻️ Refactor, ✨ Feature

#91 [fix/DB-307]: 크루 생성, 수정 이름 중복 수정
  dongsan-core/domain-rdb/src/main/java/com/dongsan/domain/domains/crew/service/CrewRdbService.java
  dongsan-external-api/src/main/java/com/dongsan/api/domains/crew/CrewInfoController.java
  dongsan-external-api/src/main/java/com/dongsan/api/domains/crew/CrewInfoFacade.java
  dongsan-external-api/src/main/java/com/dongsan/api/domains/crew/dto/response/IsNameUniqueResponse.java
Labels: 🐞 Fix

#92 [feature/DB-310]: test용 도메인 CORS 추가
  dongsan-external-api/src/main/java/com/dongsan/api/config/SecurityConfig.java
Labels: ✨ Feature

#94 [feature/DB-312]: 크루 API 수정 사항 반영
  dongsan-core/domain-rdb/src/main/java/com/dongsan/domain/domains/crew/service/CrewMemberRdbService.java
  dongsan-core/domain-rdb/src/main/java/com/dongsan/domain/domains/walkwayLog/WalkwayLogCoreRepository.java
  dongsan-core/domain-rdb/src/main/java/com/dongsan/domain/support/error/CoreErrorCode.java
  dongsan-external-api/src/main/java/com/dongsan/api/domains/crew/CrewInfoFacade.java
  dongsan-external-api/src/main/java/com/dongsan/api/domains/crew/dto/response/GetCrewInfoResponse.java
Labels: 🐞 Fix, ✨ Feature
