Repository DongSanOfficial/DongSan-Backend, pull requests merged in 2025-05, with the labels that each got.

#76 [feature/DB-252]: 닉네임 변경 API 개발
  dongsan-core/src/main/java/com/dongsan/core/domains/member/MemberRepository.java
  dongsan-core/src/main/java/com/dongsan/core/domains/member/MemberService.java
  dongsan-core/src/main/java/com/dongsan/core/domains/member/MemberWriter.java
  dongsan-domain/domain-rds/src/main/java/com/dongsan/rdb/domains/member/MemberCoreRepository.java
  dongsan-domain/domain-rds/src/main/java/com/dongsan/rdb/domains/member/MemberJpaRepository.java
  dongsan-external-api/src/main/java/com/dongsan/api/domains/member/MemberController.java
  dongsan-external-api/src/main/java/com/dongsan/api/domains/member/PatchNicknameRequest.java
Labels: ✨ Feature

#79 [refactor/DB-259]: 산책로 Repository 리팩토링
  dongsan-domain/domain-rdb/src/main/java/com/dongsan/rdb/domains/walkway/WalkwayHistoryQueryDSLRepository.java
  dongsan-domain/domain-rdb/src/main/java/com/dongsan/rdb/domains/walkway/WalkwayQueryDSLRepository.java
Labels: ♻️ Refactor

#81 [feature/DB-268]: 도메인 설계 - crew
  dongsan-core/domain-rdb/src/main/java/com/dongsan/rdb/domains/crew/domain/Crew.java
  dongsan-core/domain-rdb/src/main/java/com/dongsan/rdb/domains/crew/domain/CrewMember.java
  dongsan-core/domain-rdb/src/main/java/com/dongsan/rdb/domains/crew/domain/CrewMemberRole.java
  dongsan-core/domain-rdb/src/main/java/com/dongsan/rdb/domains/crew/domain/PrivateCrew.java
  dongsan-core/domain-rdb/src/main/java/com/dongsan/rdb/domains/crew/domain/PublicCrew.java
  dongsan-core/domain-rdb/src/main/java/com/dongsan/rdb/domains/crew/domain/RecruitComment.java
  dongsan-core/domain-rdb/src/main/java/com/dongsan/rdb/domains/crew/domain/RecruitParticipant.java
  dongsan-core/domain-rdb/src/main/java/com/dongsan/rdb/domains/crew/domain/RecruitPost.java
Labels: ✨ Feature

#83 [fix/DB-280]: 거리 기반 산책로 조회 API 에러 수정
  dongsan-external-api/src/main/java/com/dongsan/api/domains/walkway/WalkwayController.java
Labels: 🐞 Fix
